# Generated by Django 5.2 on 2025-05-04 09:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_image_alter_property_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='uploads/properties'), blank=True, default=list, size=None),
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
