# Generated by Django 5.2 on 2025-05-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_image_alter_property_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='country_code',
            new_name='state',
        ),
    ]
