# Generated by Django 5.2 on 2025-05-04 09:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_images_delete_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='uploads/properties'), size=None),
        ),
    ]
