# Generated by Django 5.2 on 2025-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_country_code_property_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
