# Generated by Django 5.2 on 2025-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/properties'),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
