# Generated by Django 5.2 on 2025-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_property_images_property_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='uploads/properties'),
        ),
    ]
