# version: '4'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/staylio-backend
    ports:
      - "8000:8000"
    env_file:
      - /.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: staylio
      POSTGRES_PASSWORD: staylio
      POSTGRES_DB: staylio

volumes:
  postgres_data: