# version: '4'

services:
  web:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/staylio-backend
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
      - daphne
  daphne:
    build: ./backend
    command: daphne --bind 0.0.0.0 -p 8002 backend.asgi:application
    ports:
      - 8002:8002

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
    - "5432:5432"

volumes:
  postgres_data: